server:
  port: 8080
  host: 0.0.0.0
  static:
    classpath:
      location: /web
  features:
    security:
      defaults:
        authenticate: true
      paths:
        - path: "/api/*"
        - path: "/api/v1/users/{}/roles"
          roles-allowed: [ "ADMIN" ]
        - path: "/auth/web/logout"
        - path: "/auth/web/principal"

security:
  providers:
    - atn:
      class: io.helidon.examples.quickstart.se.security.AtnProvider
    - atz:
      class: io.helidon.examples.quickstart.se.security.AtzProvider

db:
  source: "jdbc"
  connection:
    url: "jdbc:postgresql://localhost:5432/hr_template?useSSL=false"
    username: "postgres"
    password: "postgres"
  pool:
    connection-timeout: 3000
    max-pool-size: 10
    min-idle: 2

app:
  profile: "dev"
  frontend:
    url: "http://localhost:5173"

