server:
  port: 8080
  host: 0.0.0.0
  static:
    classpath:
      location: /web

db:
  source: "jdbc"
  connection:
    url: "jdbc:postgresql://localhost:5432/hr_template?useSSL=false"
    username: "postgres"
    password: "postgres"
  pool:
    connection-timeout: 3000
    max-pool-size: 10
    min-idle: 2
#  statements:
#    ping: "DO 0"
#    select-all-pokemons: "SELECT id, name FROM Pokemons"

app:
  greeting: "Hello"

