server:
  port: 8080
  host: 0.0.0.0
  static:
    classpath:
      location: /web
  features:
    observe:
      enabled: true
    security:
      defaults:
        authenticate: true
      paths:
        - path: "/api/*"
        - path: "/api/v1/users/*"
          methods: [ "put","delete", "post" ]
          roles-allowed: [ "ADMIN" ]
        - path: "/auth/web/logout"

security:
  providers:
    - atn:
      class: dev.borjessons.helidon.react.template.security.AtnProvider
    - atz:
      class: dev.borjessons.helidon.react.template.security.AtzProvider

db:
  source: "jdbc"
  connection:
    url: "jdbc:postgresql://localhost:5432/hr_template"
    username: "postgres"
    password: "postgres"
    connectionTimeout: 4000

app:
  profile: "local"
