server:
  port: 8080
  static:
    classpath:
      location: /web
  features:
    security:
      defaults:
        authenticate: true
      paths:
        - path: "/web/register"
          methods: [ "get" ]
          authenticate: false
        - path: "/api/v1/users[/{*}]"
          methods: [ "get", "post", "put" ]
          roles-allowed: [ "user" ]

security:
  providers:
    - atn:
      class: io.helidon.examples.quickstart.se.security.AtnProvider

db:
  source: "jdbc"
  connection:
    url: "jdbc:postgresql://localhost:5432/hr_template?useSSL=false"
    username: "postgres"
    password: "postgres"
  pool:
    connection-timeout: 3000
    max-pool-size: 10
    min-idle: 2

app:
  greeting: "Hello"

